// Update User Password
export const CHANGEPASSWORD_REQUEST = "@user/CHANGEPASSWORD_REQUEST";
export const CHANGEPASSWORD_SUCCESS = "@user/CHANGEPASSWORD_SUCCESS";
export const CHANGEPASSWORD_FAILED = "@user/CHANGEPASSWORD_FAILED";

//Update User Info
export const UPDATE_USERINFO_REQUEST = "@user/UPDATE_USERINFO_REQUEST";
export const UPDATE_USERINFO_SUCCESS = "@user/UPDATE_USERINFO_SUCCESS";
export const UPDATE_USERINFO_FAILED = "@user/UPDATE_USERINFO_FAILED";

//Get User Info
export const GET_USERINFO_REQUEST = "@user/GET_USERINFO_REQUEST";
export const GET_USERINFO_SUCCESS = "@user/GET_USERINFO_SUCCESS";
export const GET_USERINFO_FAILED = "@user/GET_USERINFO_FAILED";

//Get 2Fa Code
export const GET_2FACODE_REQUEST = "@user/GET_2FACODE_REQUEST";
export const GET_2FACODE_SUCCESS = "@user/GET_2FACODE_SUCCESS";
export const GET_2FACODE_FAILED = "@user/GET_2FACODE_FAILED";

//Update 2FaCode Info
export const UPDATE_2FACODE_REQUEST = "@user/UPDATE_2FACODE_REQUEST";
export const UPDATE_2FACODE_SUCCESS = "@user/UPDATE_2FACODE_SUCCESS";
export const UPDATE_2FACODE_FAILED = "@user/UPDATE_2FACODE_FAILED";