export { default as HomeFUBI } from "./HomeFUBI";
export { default as InvestmentFUBI } from "./InvestmentFUBI";
export { default as SwapFUBI } from "./SwapFUBI";
export { default as DashboardFUBI} from "./Dashboard";
export { default as TransactionHistory } from "./TransactionHistory";
export { default as Affiliates } from "./Affiliates";
export { default as FubiToken } from "./FubiToken";
export { default as Tokenomics } from "./Tokenomics";
export { default as RoadMap} from "./Roadmap";
export { default as WithdrawFubi} from "./WithdrawFubi";